"""
PartType0: Gas
PartType1: Grains(Epstein/Stokes and charged particles)
PartType2: Grains(Epstein/Stokes) / Star from the IC
PartType3: Super-particles
PartType4: Stars / Star from gas
PartType5: Black holes or Collisioness particles
"""

function _read_gizmo_base!(data :: ParticleDataFrame, PartGroup :: HDF5.Group; record_columns :: Set{String} = Set{String}())
    Npart = data.params["NumPartType"]
    pid_src = read(PartGroup, "ParticleIDs")
    @assert length(pid_src) == Npart
    map!(Int64, data[!, :ParticleIDs], pid_src)  

    coordinate_dset = PartGroup["Coordinates"]
    @assert size(coordinate_dset, 1) == 3
    data[!, :x] = coordinate_dset[1, :]
    data[!, :y] = coordinate_dset[2, :]
    data[!, :z] = coordinate_dset[3, :]

    velocity_dset = PartGroup["Velocities"]
    @assert size(velocity_dset, 1) == 3
    data[!, :vx] = velocity_dset[1, :]
    data[!, :vy] = velocity_dset[2, :]
    data[!, :vz] = velocity_dset[3, :]

    if haskey(PartGroup, "Masses")
        data[!, :m] = read(PartGroup, "Masses")
        data.params["TotalMassType"] = sum(data[!, :m])
    else
        @assert haskey(data.params, "MassPerParticleType") "Missing MassPerParticleType and no Masses dataset."
        mpp = data.params["MassPerParticleType"]
        data[!, :m] = fill(mpp, Npart)
        data.params["TotalMassType"] = mpp * Npart
    end
    
    if data.params["PartType"] == "PartType0"
        data[!, :rho] = read(PartGroup, "Density")
        data[!, :h] = read(PartGroup, "SmoothingLength")
    end    
    data[!, :dt] = read(PartGroup, "TimeStep")

    push!(record_columns, "ParticleIDs", "Coordinates", "Velocities", "Masses", "Density", "SmoothingLength", "TimeStep")
    return nothing
end

function _read_gizmo_dust!(data :: ParticleDataFrame, PartGroup :: HDF5.Group; record_columns :: Set{String} = Set{String}())
    if data.params["PartType"] == "PartType0"
        mC_dset  = PartGroup["CarbonDustMass"]
        mSi_dset = PartGroup["SilicateDustMass"]

        @assert ndims(mC_dset) == ndims(mSi_dset)
        @assert size(mC_dset)  == size(mSi_dset)

        nd = ndims(mC_dset)

        if nd == 1
            data[!, :mC]  = read(mC_dset)   # Vector length N
            data[!, :mSi] = read(mSi_dset)
            data.params["NumDustSpecies"] = 1
        elseif nd == 2
            K = size(mC_dset, 1)            # number of dust size bins/species
            for i in 1:K
                data[!, Symbol("mC_$(i)")]  = mC_dset[i, :]     # Vector length N
                data[!, Symbol("mSi_$(i)")] = mSi_dset[i, :]
            end
            data.params["NumDustSpecies"] = K
        else
            @warn "Skip dust: unsupported ndims=$nd"
            return nothing
        end

        push!(record_columns, "CarbonDustMass", "SilicateDustMass")
    end
    return nothing
end

function _read_gizmo_ChemicalAbundances!(data :: ParticleDataFrame, PartGroup :: HDF5.Group; record_columns :: Set{String} = Set{String}())
    if data.params["PartType"] == "PartType0"
        χ = PartGroup["ChemicalAbundancesSG"]
        data[!,"χH2"] = χ[1,:]            # Defined as nH2/nH
        data[!,"χH+"] = χ[2,:]            # Defined as nH+/nH
        data[!,"χCO"] = χ[3,:]            # Defined as nCO/nH
        push!(record_columns, "ChemicalAbundancesSG")
    end
    return nothing
end

function _read_gizmo_ThermalDynamics!(data :: ParticleDataFrame, PartGroup :: HDF5.Group; record_columns :: Set{String} = Set{String}())
    if data.params["PartType"] == "PartType0"
        data[!, :"InternalEnergy"] = read(PartGroup, "InternalEnergy")
        push!(record_columns, "InternalEnergy")
    end
    return nothing
end

"""
    read_gizmo(filename::String;
               Full_data :: Bool = true,
               ThermalDynamics :: Bool = true,
               dust :: Bool = true,
               ChemicalAbundances :: Bool = true,
               extra_columns :: AbstractVector{String} = String[]) :: Vector{ParticleDataFrame}
Reading the HDF5-format dumpfiles generated by GIZMO to a list of `ParticleDataFrame`

# Parameters 
- `filename::String`: Name of the file to be loaded.

# Keyword Arguments
- `Full_data`: When `true`, ingest every remaining dataset not already handled by the readers
  above (with automatic splitting/binding as described).
- `ThermalDynamics`: Read thermal/energy-related columns where available (gas only).
- `dust`: Read dust-related columns where available (gas only).
- `ChemicalAbundances`: Read chemical-abundance fractions where available (gas only).

# Returns
- `ParticleDataFrame` or `Vector`: ParticleDataFrame or Array of ParticleDataFrames
"""
function read_gizmo(filename::String;
    Full_data :: Bool = true,
    ThermalDynamics :: Bool = true,
    dust :: Bool = true,
    ChemicalAbundances :: Bool = true,
    extra_columns :: AbstractVector{String} = String[]) :: Vector{ParticleDataFrame}
    # Get general header
    Header = h5readattr(filename, "Header")
    Header["udist"] = 3.085678e21    # kpc --> cm
    Header["umass"] = 1.989e43       # 10^10 M⊙ --> g
    Header["utime"] = 3.0842208e16   # 0.978 Gyr --> s
    Header["umagfd"] = 1.0           # Gauss --> Gauss

    # Get the number of particles for each type
    NpartTypes = map(Int64, Header["NumPart_ThisFile"])

    # Allocating an empty vector for storage result
    prdf_list = ParticleDataFrame[]
    for (i, npart) in enumerate(NpartTypes)
        if npart == 0
            continue
        end

        # Get specific header configuration
        group_key = "PartType$(i - 1)"          # PartType{0..N}
        SpecificHeader = copy(Header)           
        SpecificHeader["PartType"] = group_key
        if haskey(SpecificHeader, "NumPart_ThisFile")
            SpecificHeader["NumPartType"] = npart
        end
        if haskey(SpecificHeader, "MassTable")
            mpp = SpecificHeader["MassTable"][i]
            SpecificHeader["MassPerParticleType"] = mpp
            SpecificHeader["TotalMassType"]        = mpp * npart
        end
        for k in ("NumPart_Total_HighWord", "NumPart_Total", "NumPart_ThisFile", "MassTable")
            haskey(SpecificHeader, k) && delete!(SpecificHeader, k)
        end

        # Generate empty ParticleDataFrame
        prdf = ParticleDataFrame(DataFrame(ParticleIDs = zeros(Int64, SpecificHeader["NumPartType"])), SpecificHeader)

        # Push to result array
        push!(prdf_list, prdf)
    end
    ignore_column = Set{String}()

    # Open files
    h5open(filename, "r") do f
        empty!(ignore_column)
        for i in eachindex(prdf_list)
            prdf = prdf_list[i]
            group_key = prdf.params["PartType"]
            PartGroup = f[group_key]

            # Read basic SPH data
            _read_gizmo_base!(prdf, PartGroup, record_columns = ignore_column)
            
            # Read ThermalDynamics-related columns
            if Full_data || ThermalDynamics
                _read_gizmo_ThermalDynamics!(prdf, PartGroup, record_columns = ignore_column)
            end

            # Read Dust-related columns
            if Full_data || dust
                _read_gizmo_dust!(prdf, PartGroup, record_columns = ignore_column)
            end

            # Read ChemicalAbundances-related columns
            if Full_data || ChemicalAbundances
                _read_gizmo_ChemicalAbundances!(prdf, PartGroup, record_columns = ignore_column)
            end

            # Get other columns
            if Full_data
                for dict_key in collect(keys(PartGroup))
                    if dict_key in ignore_column
                        continue
                    end

                    dset = PartGroup[dict_key]
                    size_data = size(dset)

                    if length(size_data) == 1
                        prdf[!, dict_key] = read(dset)
                    elseif length(size_data) == 2
                        num_rows = size_data[1]
                        dkeys = [dict_key * "_$n" for n in 1:num_rows]
                        for k in 1:num_rows
                            prdf[!, dkeys[k]] = dset[k, :]
                        end
                    end
                end
            elseif !isempty(extra_columns)
                for column in extra_columns
                    if !(column in ignore_column)
                        if haskey(PartGroup, column)
                            A = PartGroup[column]
                            if ndims(A) == 1
                                prdf[!, column] = read(A)
                            elseif ndims(A) == 2
                                K, N = size(A)
                                for k in 1:K
                                    prdf[!, string(column, "_", k)] = A[k, :] 
                                end
                            else
                                @warn "Skip $column: unsupported ndims=$(ndims(A))"
                            end  
                        end
                    end   
                end
            end
        end
    end
    return prdf_list
end